#!/bin/bash
set -euo pipefail

# GitHub Project Management Session Start Hook
# This hook integrates Claude Code sessions with GitHub Issues and Projects

# Only run in remote (web) environment
if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]; then
  exit 0
fi

# Read session metadata from stdin
SESSION_DATA=$(cat)
SESSION_ID=$(echo "$SESSION_DATA" | jq -r '.session_id // "unknown"')
SOURCE=$(echo "$SESSION_DATA" | jq -r '.source // "startup"')
CWD=$(echo "$SESSION_DATA" | jq -r '.cwd // "."')

# Log file for debugging
LOG_FILE="$HOME/.claude/github-integration.log"
mkdir -p "$(dirname "$LOG_FILE")"

log() {
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" >> "$LOG_FILE"
}

log "=== Session Start Hook Triggered ==="
log "Session ID: $SESSION_ID"
log "Source: $SOURCE"
log "CWD: $CWD"

# Install GitHub CLI if not present
if ! command -v gh &> /dev/null; then
  log "Installing GitHub CLI..."
  mkdir -p "$HOME/.local/bin"
  cd "$HOME/.local/bin"

  curl -sL https://github.com/cli/cli/releases/download/v2.40.1/gh_2.40.1_linux_amd64.tar.gz -o gh.tar.gz
  tar -xzf gh.tar.gz --strip-components=2 gh_2.40.1_linux_amd64/bin/gh
  rm gh.tar.gz

  export PATH="$HOME/.local/bin:$PATH"
  echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$CLAUDE_ENV_FILE"
  log "GitHub CLI installed successfully"
else
  log "GitHub CLI already installed"
fi

# Ensure gh is in PATH
export PATH="$HOME/.local/bin:$PATH"

# Check for GitHub token
if [ -z "${GITHUB_TOKEN:-}" ]; then
  log "WARNING: GITHUB_TOKEN not set. GitHub integration will not work."
  log "Please set GITHUB_TOKEN in your Claude Code settings."
  echo "⚠️  GitHub integration requires GITHUB_TOKEN environment variable"
  echo "   Add it to your Claude Code settings to enable session/task tracking"
  exit 0
fi

# Authenticate gh CLI
echo "$GITHUB_TOKEN" | gh auth login --with-token 2>> "$LOG_FILE" || {
  log "ERROR: Failed to authenticate with GitHub"
  exit 0
}

log "GitHub CLI authenticated successfully"

# Get repository information
cd "$CWD"
REPO=$(gh repo view --json nameWithOwner -q .nameWithOwner 2>> "$LOG_FILE" || echo "")

if [ -z "$REPO" ]; then
  log "ERROR: Could not determine repository"
  exit 0
fi

log "Repository: $REPO"

# Get current branch
BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
log "Branch: $BRANCH"

# Create session issue
SESSION_DATE=$(date '+%Y-%m-%d %H:%M:%S')
ISSUE_TITLE="🤖 Claude Code Session - ${SESSION_DATE}"
ISSUE_BODY="## Session Information

- **Session ID**: \`${SESSION_ID}\`
- **Started**: ${SESSION_DATE}
- **Branch**: \`${BRANCH}\`
- **Source**: ${SOURCE}
- **Repository**: ${REPO}

This issue tracks work done in this Claude Code session.

---
*Auto-generated by Claude Code Session Hook*"

log "Creating session issue..."
ISSUE_NUMBER=$(gh issue create \
  --repo "$REPO" \
  --title "$ISSUE_TITLE" \
  --body "$ISSUE_BODY" \
  --label "claude-session" \
  2>> "$LOG_FILE" | grep -oP '#\K\d+' || echo "")

if [ -n "$ISSUE_NUMBER" ]; then
  log "Created session issue #$ISSUE_NUMBER"

  # Store issue number for later reference
  echo "export CLAUDE_SESSION_ISSUE=$ISSUE_NUMBER" >> "$CLAUDE_ENV_FILE"
  echo "export CLAUDE_SESSION_REPO=$REPO" >> "$CLAUDE_ENV_FILE"

  # Try to add to project (find first project or skip if none exists)
  PROJECT_NUMBER=$(gh project list --owner "$(echo "$REPO" | cut -d'/' -f1)" --format json 2>> "$LOG_FILE" | \
    jq -r '.[0].number // empty' || echo "")

  if [ -n "$PROJECT_NUMBER" ]; then
    log "Adding issue to project #$PROJECT_NUMBER..."
    gh project item-add "$PROJECT_NUMBER" \
      --owner "$(echo "$REPO" | cut -d'/' -f1)" \
      --url "https://github.com/$REPO/issues/$ISSUE_NUMBER" \
      2>> "$LOG_FILE" || log "Could not add to project (may not have permissions)"
  else
    log "No projects found. Issue created but not added to any project."
  fi

  echo "✅ Session tracked: https://github.com/$REPO/issues/$ISSUE_NUMBER"
else
  log "ERROR: Failed to create session issue"
fi

log "=== Session Start Hook Completed ==="
